name: API Manager Build with Test

on: [push]

jobs:
  build-without-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml -Dmaven.test.skip=true

  build-segment-1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-api-common

  build-segment-1.1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-api-change-endpoint

  build-segment-1.2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-api-product

  build-segment-1.3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-api-lifecycle

  build-segment-1.4:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-email-secondary-userstore-tests

  build-segment-2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-CORS-tests

  build-segment-2.0:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-samples
        
  build-segment-2.1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-publisher-tests

  build-segment-2.2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-store-tests
        
  build-segment-2.3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-graphql
