name: API Manager Build with Test

on: [push]

jobs:
  build-without-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml -Dmaven.test.skip=true

  build-segment-1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-api-common

  build-segment-2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-api-change-endpoint

  build-segment-3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-api-product

  build-segment-4:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-api-lifecycle

  build-segment-5:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-email-secondary-userstore-tests

  build-segment-6:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-CORS-tests

  build-segment-7:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-samples
        
  build-segment-8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-publisher-tests

  build-segment-9:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-store-tests
        
  build-segment-10:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-graphql
        
  build-segment-11:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: rest-api-tests

  build-segment-12:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-mediation-tests

  build-segment-13:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-without-restarts

  build-segment-14:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-application-sharing

  build-segment-15:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-JWT-integration-tests

  build-segment-16:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-urlsafe-JWT-integration-tests
        
  build-segment-17:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-endpoint-security

  build-segment-18:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-external-idp

  build-segment-19:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-emailusername-login
   
  build-segment-20:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-workflow
        
    # - name: Build Product-Apim with Maven
    #   run: mvn clean install --file ../product-apim/pom.xml

    # - name: Set up JDK 1.8
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 1.8
    # - uses: actions/setup-node@v1
    #   with:
    #     node-version: '14.x'
    # - name: Build carbon-apimgt with Test.
    #   run: mvn clean install --file pom.xml
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v1.2.1
    #   with:
    #     flags: unittests
    # - name: Get carbon.apimgt.version
    #   run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout > ../CARBON_APIMGT_VERSION_FILE
    # - name: Print carbon.apimgt.version
    #   run: |
    #     echo $(cat ../CARBON_APIMGT_VERSION_FILE)
    # - name: Checkout Product-APIM
    #   uses: actions/checkout@v1
    #   with: 
    #     repository: wso2/product-apim
    #     ref: refs/heads/master
    # - name: Build Product-Apim with Maven
    #   run: mvn clean install -Dcarbon.apimgt.version=$(cat ../CARBON_APIMGT_VERSION_FILE) -fae --file ../product-apim/pom.xml
