name: API Manager Build with Test

on: [push]

jobs:
  build-without-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml -Dmaven.test.skip=true

  build-segment-1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-api-common,apim-integration-tests-api-change-endpoint

  build-segment-3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-api-product,apim-publisher-tests

  build-segment-4:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-api-lifecycle

  build-segment-5:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-email-secondary-userstore-tests

  build-segment-6:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-CORS-tests,rest-api-tests,apim-mediation-tests

  build-segment-7:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 1
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-samples,apim-store-tests, apim-integration-tests-graphql
      
  build-segment-13:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-without-restarts,apim-integration-tests-application-sharing

  build-segment-15:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-JWT-integration-tests,apim-urlsafe-JWT-integration-tests

  build-segment-17:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-endpoint-security

  build-segment-18:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Product-APIM 2
      uses: actions/checkout@v1
      with: 
        repository: malinthaprasan/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install --file ../product-apim/pom.xml
      env:
        PRODUCT_APIM_TESTS: apim-integration-tests-external-idp,apim-integration-emailusername-login,apim-integration-tests-workflow
